---
notification_email: nandanjha.navneet@gmail.com
notification_email_from: hello@blabla.com
smtp_server: xxx.xxx.xxx.xxx
interface1: bond0
interface2: bond0
unicast_src_ip_server_1: 172.31.12.251
unicast_peer_server_1: 172.31.12.252
virtual_ipaddress: 172.31.12.250
unicast_src_ip_server_2: 172.31.12.252
unicast_peer_server_2: 172.31.12.251