#this playbook is for installing mysql 5.7 on specific OS
- name: Installing mysql 5.7
  hosts: mysqlhost
  vars:
    home_dir: "/home/instance"
    non_interactive_mysql: noninteractive
    db_user: root
    db_password: Passw0rd
  tasks:


    - include: tasks/debian-dependecies.yml

    - name: Add official APT repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/ jessie mysql-5.7"


    - name: Install mysql-server
      apt:
       name: "{{ item }}"
       allow_unauthenticated: yes
       state: present
       update_cache: yes
      with_items:
      - mysql-server

    - name: Ensure mysql is running and starts on boot
      service:
       name: mysql
       state: started
       enabled: yes
      become: yes

    - name: Create `/root/.my.cnf`  with root password credentials
      template:
        src:  my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600
      become: yes


    - name: Ensure mysql root password is updated for all root accounts
      mysql_user:
       name: "{{ db_user }}"
       host: "{{ item }}"
       login_unix_socket: /var/run/mysqld/mysqld.sock
       password: "{{ db_password }}"
       priv: '*.*:ALL,GRANT'
       check_implicit_admin: true
      loop:
        - "{{ ansible_host }}"
        - 127.0.0.1
        - ::1
        - localhost
      become: yes
